config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  
  get 'uploads/new'

  get 'uploads/create'

  resources :credit_cards
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :products
  resources :uploads, only: [:new, :create]

  put 'charges/create' => 'charges#create'

end

app/models/credit_card.rb
class CreditCard < ActiveRecord::Base
  Stripe.api_key = Rails.application.secrets.stripe_secret_key
  belongs_to :user
 
  before_validation :set_last_digits
 
  attr_accessor :number
 
  validates :digits, presence: true
  validates :month, presence: true, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 12 }
  validates :year, presence: true, numericality: { greater_than_or_equal_to: DateTime.now.year }

  after_create :create_credit_card_to_stripe
 
  def set_last_digits
    if number
      number.to_s.gsub!(/\s/,'')
      self.digits ||= number.to_s.length <= 4 ? number : number.to_s.slice(-4..-1)
    end
  end

  def create_credit_card_to_stripe
    token = Stripe::Token.create(
      :card => {
        :number => digits,
        :exp_month => month,
        :exp_year => year,
        :cvc => cvc
      },
    )

    cu = Stripe::Customer.retrieve(user.customer_id)
    cu.description = "Customer for #{user.email} %>"
    cu.source = token.id
    cu.save
  end
end

app/controllers/credit_cards_controller.rb
class CreditCardsController < ApplicationController
  before_action :set_credit_card, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  # GET /credit_cards
  # GET /credit_cards.json
  def index
    @credit_cards = current_user.credit_cards
  end

  # GET /credit_cards/1
  # GET /credit_cards/1.json
  def show
  end

  # GET /credit_cards/new
  def new
    @credit_card = current_user.credit_cards.build
  end

  # GET /credit_cards/1/edit
  def edit
  end

  # POST /credit_cards
  # POST /credit_cards.json
  def create
    @credit_card = current_user.credit_cards.build(credit_card_params)

    respond_to do |format|
      if @credit_card.save
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully created.' }
        format.json { render :show, status: :created, location: @credit_card }
      else
        format.html { render :new }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /credit_cards/1
  # PATCH/PUT /credit_cards/1.json
  def update
    respond_to do |format|
      if @credit_card.update(credit_card_params)
        format.html { redirect_to @credit_card, notice: 'Credit card was successfully updated.' }
        format.json { render :show, status: :ok, location: @credit_card }
      else
        format.html { render :edit }
        format.json { render json: @credit_card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /credit_cards/1
  # DELETE /credit_cards/1.json
  def destroy
    @credit_card.destroy
    respond_to do |format|
      format.html { redirect_to credit_cards_url, notice: 'Credit card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_credit_card
      @credit_card = CreditCard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def credit_card_params
      params.require(:credit_card).permit(:digits, :month, :year, :cvc)
    end
end

app/helpers/credit_cards_helper.rb
module CreditCardsHelper
end

app/views/credit_cards/_form.html.erb
<%= form_for(@credit_card) do |f| %>
  <% if @credit_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@credit_card.errors.count, "error") %> prohibited this credit_card from being saved:</h2>

      <ul>
      <% @credit_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :digits %><br>
    <%= f.text_field :digits %>
  </div>
  <div class="field">
    <%= f.label :month %><br>
    <%= f.number_field :month %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :cvc %><br>
    <%= f.number_field :cvc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/credit_cards/edit.html.erb
<div class="wrapper">
	<h1>Editing Credit Card</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @credit_card %> |
	<%= link_to 'Back', credit_cards_path %>
</div>

app/views/credit_cards/index.html.erb
<div class="wrapper">
  <!-- <p id="notice"><%= notice %></p> -->

  <h1>Listing Credit Cards</h1>

  <table border="1", width="50%">
    <thead>
      <tr>
        <th>Digits</th>
        <th>Month</th>
        <th>Year</th>
        <th>CVC</th>
        <th>User</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @credit_cards.each do |credit_card| %>
        <tr>
          <td><%= credit_card.digits %></td>
          <td><%= credit_card.month %></td>
          <td><%= credit_card.year %></td>
          <td><%= credit_card.cvc %></td>
          <td><%= credit_card.user.email %></td>
          <td><%= link_to 'Show', credit_card %></td>
          <td><%= link_to 'Edit', edit_credit_card_path(credit_card) %></td>
          <td><%= link_to 'Destroy', credit_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% unless current_user.credit_cards.present? %>
    <%= link_to 'New Credit card', new_credit_card_path %>
  <% end %>

  <br>
  <%= link_to 'Back', root_path %>
</div>

app/views/credit_cards/new.html.erb
<div class="wrapper">
	<h1>New Credit Card</h1>

	<%= render 'form' %>

	<%= link_to 'Back', credit_cards_path %>
</div>

app/views/credit_cards/show.html.erb
<div class="wrapper">
  <!-- <p id="notice"><%= notice %></p> -->

  <p>
    <strong>Digits:</strong>
    <%= @credit_card.digits %>
  </p>

  <p>
    <strong>Month:</strong>
    <%= @credit_card.month %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= @credit_card.year %>
  </p>

  <p>
    <strong>CVC:</strong>
    <%= @credit_card.cvc %>
  </p>

  <p>
  	<strong>User:</strong>
  	<%= @credit_card.user.email %>
  </p>

  <%= link_to 'Edit', edit_credit_card_path(@credit_card) %> |
  <%= link_to 'Back', credit_cards_path %>
</div>