config/routes.rb
Rails.application.routes.draw do

  root 'products#index'
  
  get 'uploads/new'

  get 'uploads/create'

  resources :credit_cards
  devise_for :users, controllers: {
    registrations: 'users/registrations'
  }
  
  resources :products
  resources :uploads, only: [:new, :create]

  put 'charges/create' => 'charges#create'

end

app/models/product.rb
class Product < ActiveRecord::Base
	validates :name,  presence: true, uniqueness: true
  validates :price, presence: true, numericality: { greater_than: 0, less_than: 999999 }
  belongs_to :user
  # has_many :uploads
  has_attached_file :image, :styles => { :medium => "100x100>",:thumb => "100x100>" }
	
	validates_attachment 	:image, 
				:presence => true,
				:content_type => { :content_type => /\Aimage\/.*\Z/ },
				:size => { :less_than => 1.megabyte }
 
  def price_in_cents
    (price * 100).to_i
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = current_user.products.build
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = current_user.products.build(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render json: { message: "success", fileID: @product.id }, :status => 200 }
      else
        format.html { render :new }
        format.json { render json: { error: @product.errors.full_messages.join(',')}, :status => 400 }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div style="margin-left: 20px;">
  <%= simple_form_for(@product, :html => {:class => 'dropzone', multipart: true}) do |f| %>
    <% if @product.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

        <ul>
        <% @product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="field">
      <%= f.label :name %><br>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.label :price %><br>
      <%= f.text_field :price %>
    </div>
    
    <%= f.label "Drag image here" %>
    <div class="controls">
    </div>
  <% end %>
</div>

app/views/products/edit.html.erb
<div class="wrapper">
	<h1>Editing Product</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @product %> |
	<%= link_to 'Back', products_path %>
</div>

app/views/products/index.html.erb
<div class="wrapper">
  <!-- <p id="notice"><%= notice %></p> -->

  <div>
    <% if user_signed_in? %>
      <%= link_to "Logout", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to "Sign up", new_user_registration_path %> <br>
      <%= link_to "Login", new_user_session_path %>
    <% end %>
  </div>
  <h1>Listing Products</h1>

  <table border="1" width="50%">
    <thead>
      <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Image</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @products.each do |product| %>
        <tr>
          <td><%= product.name %></td>
          <td><%= product.price %></td>
          <td><%= link_to image_tag(product.image.url(:thumb), class: 'media-object'), product.image.url(:thumb), target: '_blank' %></td>
          <td align="center">
              <%= link_to 'Show', product %>
              <% if user_signed_in? %>
                <% if product.user == current_user %>
                  <%= link_to 'Edit', edit_product_path(product) %>
                  <%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %>
                <% end %>
              <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <% if user_signed_in? %>
    <div data-turbolinks="false">
      <%= link_to 'New Product', new_product_path %>
    </div>
    <br>
    <div>
      <%= link_to 'Credit Card', credit_cards_path %>
    </div>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="wrapper">
	<h1>New Product</h1>

	<%= render 'form' %>

	<%= link_to 'Back', products_path %>
</div>

app/views/products/show.html.erb
<div class="wrapper">
	<!-- <p id="notice"><%= notice %></p> -->

	<p>
	  <strong>Name:</strong>
	  <%= @product.name %>
	</p>

	<p>
	  <strong>Price:</strong>
	  <%= @product.price %>
	</p>

	<p>
		<strong>Price:</strong>
		<%= image_tag @product.image.url(:thumb) %>
	</p>
	<br>
	 
	<% if user_signed_in? %>
		<% if current_user.credit_cards.reject{ |card| card.new_record? }.any? %>
		  <%= button_to "Pay", charges_create_path(id: @product.id), method: :put, data: { 'disable-with' => 'Please wait ...' } %>
		<% else %>
			<%= link_to "Create Credit Card", new_credit_card_path %>
		<% end %>
		
		<br>
		<% if @product.user == current_user %>
			<%= link_to 'Edit', edit_product_path(@product) %>
		<% end %>
	<% end %>
	<br>
	<%= link_to 'Back', products_path %>
</div>